name: Deploy Binance AI Short Bot

on:
  push:
    branches:
      - main # 只在main上push触发部署
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - LICENSE

jobs:
  deploy:
    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚本

    steps: # 自动化步骤
      - uses: actions/checkout@v2 
      - name: 下载源码 
        uses: appleboy/scp-action@master 
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "./"
          target: "/home/ubuntu/censor-words"
      - name: 安装代码
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ubuntu/censor-words
            npm install
            npm run build
 